spring:
  application:
    name: gateway

  config:
    import: "consul:"

  cloud:
    gateway:
      routes:
        - id: iam-service
          uri: lb://iam-service
          predicates:
            - Path=/iam/**
          filters:
            - StripPrefix=1

        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/storage/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=1

        - id: elasticsearch-service
          uri: lb://elasticsearch-service
          predicates:
            - Path=/elasticsearch/**
          filters:
            - StripPrefix=1

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        enabled: true
        health-check-path: /actuator/health

server:
  port: 8686

springdoc:
  swagger-ui:
    enabled: true
    urls:
      - url: http://localhost:8888/swagger-doc/v3/api-docs/iam
        name: IAM API

      - url: http://localhost:8080/swagger-doc/v3/api-docs/storage
        name: Storage API